#SET = 0;
#GET = 1;

### POST set key
POST https://localhost:8443/execute
Content-Type: application/json

{
  "keyword": 0,
  "entry": {
    "key": "key",
    "value": "SGVsbG8sIFdvcmxkIQ=="
  }
}

###

### POST get key
POST https://localhost:8443/execute
Content-Type: application/json

{
  "keyword": 1,
  "entry": {
    "key": "key",
    "value": ""
  }
}

###